default_context:
  project_name: 'obturbo'
  project_slug: 'obturbo'
  domain_main: 'obturbo.com'
  domain_staging: 'stag.obturbo.com'
  docker_swarm_stack_name_main: 'obturbo-com'
  docker_swarm_stack_name_staging: 'stag-obturbo-com'
  secret_key: '7aa63eaf9d52b88ac16c13572e12fe3507f39262afcbc3cc73d346452e6a894a'
  first_superuser: 'tech@obturbo.com'
  first_superuser_password: '7951a1170ae8ac7bf55568efcfb22a212eaacba0923b8378f8fefa939102e460'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.obturbo.com", "https://stag.obturbo.com", "https://obturbo.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '465'
  smtp_host: 'mail.obturbo.com'
  smtp_user: 'tech@obturbo.com'
  smtp_password: '!@Obturbo13579'
  smtp_emails_from_email: 'tech@obturbo.com'
  postgres_password: '04ce4ef88b3f6a1661642c42e0498c937491d79c651d1643bcf0fcf486079afe'
  pgadmin_default_user: 'tech@obturbo.com'
  pgadmin_default_user_password: '7951a1170ae8ac7bf55568efcfb22a212eaacba0923b8378f8fefa939102e460'
  traefik_constraint_tag: 'obturbo.com'
  traefik_constraint_tag_staging: 'stag.obturbo.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:7951a1170ae8ac7bf55568efcfb22a212eaacba0923b8378f8fefa939102e460'
  sentry_dsn: 'https://b43f962f596c48f484fbb9444f5ab44b@o190918.ingest.sentry.io/5756166'
  docker_image_prefix: 'obt_'
  docker_image_backend: 'obt_backend'
  docker_image_celeryworker: 'obt_celeryworker'
  docker_image_frontend: 'obt_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
